#!/bin/bash
# menu for archbase modified to work in ~/.local/bin

info_option() {
	echo ""
	echo ""
	cat archbase/info.txt | most
}

menu_option_two() {
  tput setaf 3
  echo ""
  echo " Install rsync & reflector, fix mirrors,"
  echo " update distro, setup vim to $HOME. "
  tput sgr0
  sh archbase/phase1.sh
}

menu_option_three() {
  tput setaf 3
  echo ""
  echo "  Installing micro and copy files to $HOME. "
  tput sgr0
  sh archbase/su/micro-setup.sh
}

menu_option_four() {
  tput setaf 3
  echo ""
  echo "  Installing pkgs and make directories for $HOME. "
  echo "  Check package list and edit install-pkgs.sh before execution. "
  tput sgr0
  sh archbase/phase2.sh
}

menu_option_five() {
  tput setaf 3
  echo ""
  echo "  ** Restoring user xfce4 files **"
  tput sgr0
  sh archbase/xfce-restore.sh
}

menu_option_six() {
  tput setaf 3
  echo ""
  echo "  Install alacritty terminal to $HOME.  "
  tput sgr0
  sh archbase/su/alacritty-setup.sh
}

zsh_option() {
  tput setaf 3
  echo ""
  echo "  Setup basic zsh shell to $HOME.  "
  tput sgr0
  sh archbase/su/zsh-setup.sh
}

remove_option() {
  tput setaf 3
  echo ""
  echo "  Remove selected packages in helpers/rm-pkgs.sh "
  tput sgr0
  sh archbase/helpers/rm-pkgs.sh
}

press_enter() {
  echo ""
  echo -n "  Press Enter to continue "
  read
  clear
}

incorrect_selection() {
  tput setaf 1
  echo ""
  echo ""
  echo "      #######################"
  echo "         ERROR! Try again.   "
  echo "      #######################"
  tput sgr0
}

until [ "$selection" = "0" ]; do
  clear
tput setaf 3
  echo ""
  echo "    1  -  Read install info. "
  echo "    2  -  Fix mirrors, update distro,setup vim and Reboot."
  echo "    3  -  Install and setup micro editor (nano alternative). "
  echo "    4  -  Install user programs. Check and edit install-pkgs.sh before choosing."
  echo "    5  -  Restore user xfce4 files. * MOUNT DATA1 *"
  echo "    6  -  Install and setup alacritty terminal. "
  echo "    7  -  Install and setup basic zsh."
  echo "    8  -  Remove packages. Edit pkg list before this."
  echo "    0  -  Exit"
  echo ""
  echo -n "  Enter selection: "
  read selection
  echo ""
tput sgr0
  case $selection in
    1 ) clear ; info_option ; press_enter ;;
    2 ) clear ; menu_option_two ; press_enter ;;
    3 ) clear ; menu_option_three ; press_enter ;;
    4 ) clear ; menu_option_four ; press_enter ;;
    5 ) clear ; menu_option_five ; press_enter ;;
    6 ) clear ; menu_option_six ; press_enter ;;
    7 ) clear ; zsh_option ; press_enter ;;
    8 ) clear ; remove_option ; press_enter ;;
    0 ) clear ; exit ;;
    * ) clear ; incorrect_selection ; press_enter ;;
  esac
done