#!/bin/bash

# KDE folders in $HOME and install programs I use
##############################################################

## mkdirs in ~/
./kde/kde-folders

## install pkgs
./kde/kde-pkgs

## restore files
./kde/kde-restore 

