#!/bin/bash

# alias for menu-bin to .bashrc
echo "#=========================" >> $HOME/.bashrc
echo "# alias for archbase menu" >> $HOME/.bashrc
echo "alias menu='menu-bin'" >> $HOME/.bashrc
echo "PATH=$HOME/bin:$PATH" >> $HOME/.bashrc

##  packages needed:

## most (replaces the less pager)
		if pacman -Qi most &> /dev/null; then
		tput setaf 2;echo " most installed ";tput sgr0
	else
		tput setaf 3;echo " Installing rsync ";tput sgr0
		sudo pacman -S --noconfirm --needed most
	fi

## need rsync:
		if pacman -Qi rsync &> /dev/null; then
		tput setaf 2;echo " rsync installed ";tput sgr0
	else
		tput setaf 3;echo " Installing rsync ";tput sgr0
		sudo pacman -S --noconfirm --needed rsync
	fi
## need reflector:
		if pacman -Qi reflector &> /dev/null; then
		tput setaf 2;echo " reflector installed ";tput sgr0
	else
		tput setaf 3;echo " Installing reflector ";tput sgr0
		sudo pacman -S --noconfirm reflector
	fi

# install & setup vim files
./su/vim-setup
