#!/bin/bash
## Menu for archbase

## choices
update-OS() {
  tput setaf 3
  echo ""
  echo "  Update mirrors and Arch distro "
  echo "  Reboot system  "
  tput sgr0
  ./update-distro
}

phase1() {
  tput setaf 3
  echo ""
  echo " Setup vim & bash files"
  tput sgr0
  ./phase1
}

xfce-phase() {
  tput setaf 3
  echo ""
  echo "  Installing XFEC pkgs & home files.  "
  echo "  Check package list and edit install-pkgs.sh before execution. "
  tput sgr0
  ./xfce-phase
}

kde-phase() {
  tput setaf 3
  echo ""
  echo "  Installing pkgs create directories for kde $HOME. "
  echo "  Check package list and edit install-pkgs.sh before execution. "
  tput sgr0
  ./kde-phase
}

micro() {
  tput setaf 3
  echo ""
  echo "  Installing micro and copy files to $HOME. "
  tput sgr0
  ./setup/micro-setup
}

bspwm() {
  tput setaf 3
  echo ""
  echo "  Install and setup bspwm files to $HOME.  "
  tput sgr0
  ./setup/bspwm
}

zsh() {
  tput setaf 3
  echo ""
  echo "  Setup basic zsh shell to $HOME.  "
  tput sgr0
  ./setup/zsh-setup
}

remove() {
  tput setaf 3
  echo ""
  echo "  Remove selected packages in helpers/rm-pkgs.sh "
  tput sgr0
  ./helpers/rm-pkgs
}

press_enter() {
  echo ""
  echo -n "  Press Enter to continue "
  read
  clear
}

incorrect_selection() {
  tput setaf 1
  echo ""
  echo ""
  echo "      #######################"
  echo "         ERROR! Try again.   "
  echo "      #######################"
  tput sgr0
}

until [ "$selection" = "0" ]; do
  clear
tput setaf 3
  echo ""
  echo "    1  -  Update Mirrors & Arch Distro- Reboot OS. "
  echo "    2  -  Install vim & bash files. "
  echo "    3  -  Restore xfce and configs. "
  echo "    4  -  Restore plasma and configs. "
  echo "    5  -  Install micro editor and folders."
  echo "    6  -  Install and setup bspwm. "
  echo "    7  -  Install and setup basic zsh."
  echo "    8  -  Remove packages. Edit pkg list before this."
  echo "    0  -  Exit"
  echo ""
  echo -n "  Enter selection: "
  read selection
  echo ""
tput sgr0
  case $selection in
    1 ) clear ; update-OS ; press_enter ;;
    2 ) clear ; phase1 ; press_enter ;;
    3 ) clear ; xfce-phase ; press_enter ;;
    4 ) clear ; kde-phase ; press_enter ;;
    5 ) clear ; micro ; press_enter ;;
    6 ) clear ; bspwm ; press_enter ;;
    7 ) clear ; zsh ; press_enter ;;
    8 ) clear ; remove ; press_enter ;;
    0 ) clear ; exit ;;
    * ) clear ; incorrect_selection ; press_enter ;;
  esac
done
