#!/bin/bash

## install most, update mirrors. update distro & reboot OS
############################################################

## most pager, replaces the less pager
sudo pacman -S most --noconfirm --needed

## folder in place ?
[ -d $HOME"/.local/bin" ] || mkdir -p $HOME"/.local/bin"

## copy script to folder
cp -arf helpers/menu-bin $HOME/.local/bin/

## update mirrors
tput setaf 6;echo " Updating mirror list. ";tput sgr0

sudo reflector --age 6 --latest 20  --fastest 20 --threads 5 --sort rate\
 --protocol https --save /etc/pacman.d/mirrorlist
#sudo reflector -f 30 -l 30 --number 10 --sort rate\
# --verbose --save /etc/pacman.d/mirrorlist

sleep 1

# use all cores in building pkgs
./helpers/use-all-cores-makepkg-conf

# update distro
sudo pacman -Syyu --color auto

# Reboot
tput setaf 6;echo "";echo ""
echo "****************************"
echo "     TIME TO REBOOT OS      "
echo "****************************"
sleep 3
sudo reboot
