#!/bin/bash

# XFCE folders in $HOME and install programs I use
##############################################################

## exec: personal-folders.sh and arco-pkg.sh

##       mkdirs in ~/
./xfce/xfce-folders

##       install pkgs
./xfce/xfce-pkgs

##       restore files
./xfce/xfce-restore
