#!/bin/bash

# Create personal folders in $HOME and install programs I use
##############################################################

# exec: personal-folders.sh and arco-pkg.sh

#       mkdirs in ~/
./xfce-folders

#       install pkgs
./xfce-pkgs
