#!/bin/bash

# script to set up vim before main install/restore

# Install neovim

	# checking if neovim is installed
		if pacman -Qi neovim &> /dev/null; then
		tput setaf 2;echo " neovim is installed ";tput sgr0
	else
		tput setaf 3;echo " Installing neovim ";tput sgr0
		sudo pacman -S --noconfirm neovim
	fi

# make directory
[ -d $HOME"/.config/nvim" ] || mkdir -p $HOME"/.config/nvim"

# copy neovim files
cp -arf conf/nvim $HOME/.config/

## vim not used now
#cp -arf conf/.vim $HOME/.vim/
#cp -arf conf/.vimrc $HOME/

tput setaf 6
echo "-----------------------------"
echo "   Setup of vim done.        "
echo "---------------------------- "
tput sgr0
