#!/bin/bash
###############################################
#    **** FOR XFCE ARCH BASED DISTROS *****
###############################################
#	script to restore home files after distro install

tput setaf 11
echo "================================"
echo "Restoring home files for user."
echo "================================"
tput sgr0

rsync -av /run/media/whw/Data1/arcolinux/xfce/\
.{bashrc,bash_profile,gitconfig,vimrc,gitconfig,} $HOME/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.bash/ $HOME/.bash/
rsync -av /run/media/whw/Data1/arcolinux/xfce/Bash/ $HOME/Bash/
rsync -av /run/media/whw/Data1/arcolinux/xfce/bin/ $HOME/bin/
rsync -av /run/media/whw/Data1/arcolinux/xfce/Documents/ $HOME/Documents/
rsync -av /run/media/whw/Data1/arcolinux/xfce/helpers/ $HOME/helpers/
rsync -av /run/media/whw/Data1/arcolinux/xfce/Python/ $HOME/Python/
rsync -av /run/media/whw/Data1/arcolinux/xfce/wallpaper/ $HOME/wallpaper/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.local/share/\
{icons,themes,xfce4-panel-profiles} $HOME/.local/share/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.vim/ $HOME/.vim/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.ssh/ $HOME/.ssh/

#	xfce keybinds and xfce4-terminal 
rsync -av /run/media/whw/Data1/arcolinux/xfce/xfce4-keyboard-shortcuts.xml\
 $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/ 

####  COPY ICONS AND THEMES FROM DATA1 W FILEMANGR  ####################

##  config folders
#rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/ $HOME/.config/

###  just in case of snafu
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/alacritty/ $HOME/.config/alacritty/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/bspwm/ $HOME/.config/bspwm/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/geany/ $HOME/.config/geany/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/gtk-3.0/bookmarks $HOME/.config/gtk-3.0/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/micro/ $HOME/.config/micro/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/polybar/ $HOME/.config/polybar/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/nvim/ $HOME/.config/nvim/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/rofi/ $HOME/.config/rofi/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/starship.toml $HOME/.config/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/sublime-text-3/ $HOME/.config/sublime-text-3/
rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/Thunar/uca.xml $HOME/.config/Thunar/
##rsync -av /run/media/whw/Data1/arcolinux/xfce/.config/xfce4/ $HOME/.config/xfce4/

tput setaf 3
echo "######################################"
echo "###      Programs Installed       ####"
echo "######################################"
tput sgr0
