#!/bin/bash
# Arch-base XFCE folders
########################################################################

#xdg-user-dirs-update
xdg-user-dirs-update --force

tput setaf 2
echo "Creating personal folders. "
tput sgr0

[ -d $HOME"/bash" ] || mkdir -p $HOME"/bash"
[ -d $HOME"/bin" ] || mkdir -p $HOME"/bin"
[ -d $HOME"/Documents" ] || mkdir -p $HOME"/Documents"
[ -d $HOME"/helpers" ] || mkdir -p $HOME"/helpers"
[ -d $HOME"/Python" ] || mkdir -p $HOME"/Python"
[ -d $HOME"/repos" ] || mkdir -p $HOME"/repos"
[ -d $HOME"/wallpaper" ] || mkdir -p $HOME"/wallpaper"
[ -d $HOME"/.config/alacritty" ] || mkdir -p $HOME"/.config/alacritty"
[ -d $HOME"/.config/Bitwarden" ] || mkdir -p $HOME"/.config/Bitwarden"
[ -d $HOME"/.config/BraveSoftware" ] || mkdir -p $HOME"/.config/BraveSoftware"
[ -d $HOME"/.config/bspwm" ] || mkdir -p $HOME"/.config/bspwm"
[ -d $HOME"/.config/geany/colorschemes" ] || mkdir -p $HOME"/.config/geany/colorschemes"
[ -d $HOME"/.config/micro" ] || mkdir -p $HOME"/.config/micro"
[ -d $HOME"/.config/nvim" ] || mkdir -p $HOME"/.config/nvim"
[ -d $HOME"/.config/polybar" ] || mkdir -p $HOME"/.config/polybar"
[ -d $HOME"/.config/rofi" ] || mkdir -p $HOME"/.config/rofi"
[ -d $HOME"/.config/sakura" ] || mkdir -p $HOME"/.config/sakura"
#[ -d $HOME"/.config/sublime-text" ] || mkdir -p $HOME"/.config/sublime-text-3"
[ -d $HOME"/.config/termite" ] || mkdir -p $HOME"/.config/termite"
[ -d $HOME"/.config/Thunar" ] || mkdir -p $HOME"/.config/Thunar"
[ -d $HOME"/.ssh" ] || mkdir -p $HOME"/.ssh"
[ -d $HOME"/.vim" ] || mkdir -p $HOME"/.vim"
#[ -d $HOME"/zim" ] || mkdir -p $HOME"/zim"

tput sgr0
tput setaf 6
echo "################################################################"
echo "###       personal folders created or existed already       ####"
echo "################################################################"
tput sgr0
