#!/bin/bash

##  ~/.bashrc tweaks

## Is curl installed ?
	if pacman -Qi curl &> /dev/null; then
		tput setaf 2
  		echo "   The package curl is already installed   "
      	      	echo
		tput sgr0
	else
    	tput setaf 3
    	echo "    Installing curl     "
    	echo
    	tput sgr0
    	sudo pacman -S --noconfirm curl
   fi

cd ~

## install starship prompt from website
curl -fsSL https://starship.rs/install.sh | bash

cd archbase

## add lines to bashrc 
cat conf/bash-add >> $HOME/.bashrc

[ -d $HOME"/bash" ] || mkdir -p $HOME"/bash"
[ -d $HOME"/bin" ] || mkdir -p $HOME"/bin"

##
rsync -av bash/ $HOME/bash/
rsync -av bin/ $HOME/bin/
rsync -av conf/starship.toml $HOME/.config/

tput setaf 14
echo "-----------------------"
echo "   Bashrc add done.    "
echo "---------------------- "
tput sgr0

